### ISSUE TITLE
Capture activity data from GitHub API

### ISSUE THREAD

**Issue by kbuffardi** [ChicoState/chronicle#1]
We need to be able to read activity data for a repository from GitHub's API, including:

- [ ] **Commit** including date/time it was made, author (username), lines added, lines deleted, commit message
- [x] **Issue** including date/time it was made, id#, author (username), description, assignees (usernames), date/time it was closed, username who closed it
- [x] **Pull Request** including date/time it was submitted, id #, author (username), status [approved, open, closed], reviewers (usernames), date/time it was approved, date/time it was closed
- [x] **Code Reviews** including date/time it was submitted, id # for the associated PR, reviewer (username), status [comment, approve, or request changes], description
- [x] **Comments** (those that are not code reviews) including date/time, author (username), id # of associated PR or Issue, message

**Comment by kbuffardi** [comment]
These are the most vital data to capture (along with their meta data). Let me know if you find that the API does not provide you direct access to any of these.

**Comment by kbuffardi** [comment]
@SANDESHSOBARAD can you verify whether or not the project currently collects all the above data as specified?

**Comment by SANDESHSOBARAD** [comment]
I have been checking each and every data collection, due to a rate limit I am not able to use the apis more often for cross checking. most of the data is being fetched that is specified, but I can see that the number of lines added and deleted in a commit is not being fetched,I am able to fetch the issues that are in open state. Other than that I am able to see that the app is fetching all the data. I found out the api required for number of lines added and deleted in a commit, have to see how to fit it in the code. Other than that rest all other data is being fetched as per requirement.

**Comment by kbuffardi** [comment]
@SANDESHSOBARAD let's limit the rate by just gather a *single* repository's data (rather than all repos in an organization).

By [this discussion](https://stackoverflow.com/questions/56941641/using-githubs-api-to-get-lines-of-code-added-deleted-per-commit-on-a-branch) it looks like `additions` and `deletions` are reported as attributes to the `file` variable. Once you add this data collection along with specifying just a single repository, then create a PR that closes this issue.

**Comment by kbuffardi** [comment]
Closed as replicated by other issues
